export const INCREMENT_ACTION = 'app/CounterContainer/INCREMENT_ACTION'
export const DECREMENT_ACTION = 'app/CounterContainer/ACTION_DECREMENT'
export const INCREMENT_ACTION_ASYNC = 'app/CounterContainer/INCREMENT_ACTION_ASYNC'
export const SELECTOR_COUNT = 'app/CounterContainer/SELECTOR_COUNT'
export const SELECTOR_COUNT_VALUE = 'app/CounterContainer/SELECTOR_COUNT_VALUE'
